app/history/__init__.py
from flask import Blueprint

bp = Blueprint('history', __name__)

from app.history import routes

app/history/routes.py
from flask import render_template, redirect, url_for, flash, request, session
from werkzeug.urls import url_parse
from flask_login import login_user, logout_user, current_user, login_required
from app import db
from app.history import bp
from sqlalchemy import and_, or_, not_
from app.history.forms import HistoryFilterForm, HistoryMainForm, IndicatorsForm, \
                              IndicatorItemForm, HistoryMainDiagnosForm, HistoryOtherDiagnosForm,\
                              AmbulanceMainForm, HistioryNewAmbulanceForm, ProsthesisForm,\
                              TelerentgenographyForm, PreoperativeForm,\
                              HospitalSubForm1, NewHospitalForm, HospitalSubForm2
from app.models import Histories, Clinics, Diagnoses, Patients, Indicators, HistoryEvents,\
                       IndicatorValues, Events, DiagnosesItems, Prosthesis
from datetime import datetime
from hashlib import md5
from app.history.history_tools import CreateHistory, UpdateHistory, FillHistoryForm, \
                                    AddMainDiagnos, AddOtherDiagnos, CreateAmbulance, \
                                    FillAmbulanceForm, UpdateAmbulance, CreateHospital,\
                                    UpdateHospital, FillHospitalForm



# Список историй болезни
@bp.route('/history_select', methods = ['GET','POST'])
@login_required
def history_select():

    FilterForm = HistoryFilterForm()
    page = request.args.get('page',1,type=int)

    clinic_filter_id = session.get('clinic_filter_id')
    snils_filter_hash = session.get('snils_filter_hash')
    history_list = Histories.query
    if clinic_filter_id is not None:
        history_list = history_list.filter(Histories.clinic==clinic_filter_id)

    if snils_filter_hash is not None:
        patient = Patients.query.filter(Patients.snils_hash==snils_filter_hash).first()
        if patient is not None:
            history_list = history_list.filter(Histories.patient==patient.id)


    pagination =  history_list.paginate(page,5,error_out=False)
    histories = pagination.items

    if FilterForm.submit_filter.data and FilterForm.validate_on_submit():
# Фильтрация списка
        history_list = Histories.query
        if FilterForm.clinic_filter.data != 0:
# Выбрано значение ( не All)
            history_list = history_list.filter(Histories.clinic==FilterForm.clinic_filter.data)
            session['clinic_filter_id']= FilterForm.clinic_filter.data
# Выбрано значение ALL - снять фильтр
        if FilterForm.clinic_filter.data == 0:
            session['clinic_filter_id'] = None

        if FilterForm.snils_filter.data != '':
# Выбрано значение ( не All)
            digest = md5(FilterForm.snils_filter.data.lower().encode('utf-8')).hexdigest()
            patient = Patients.query.filter(Patients.snils_hash==digest).first()
            if patient != None:
                history_list = history_list.filter(Histories.patient==patient.id)
                session['snils_filter_hash']= digest
            else:
                flash('Пациента с указанным СНИЛС не существует', category='warning')
                session['snils_filter_hash'] = None


# Выбрано значение ALL - снять фильтр
        if FilterForm.snils_filter.data == '':
            session['snils_filter_hash'] = None

        pagination =  history_list.paginate(page,5,error_out=False)
        histories = pagination.items


    return render_template('history/history_select.html', HistoryFilterForm=FilterForm,
                            title='Поиск истории болезни', histories=histories, pagination=pagination)


# Редактирование истории болезни
@bp.route('/history_edit/<h>/<pill>', methods = ['GET','POST'])
# Параметры:
# h - Histories.id
# pill - номер закладки в форме
@login_required
def history_edit(h, pill):
    history = Histories.query.get(h)

    MainForm = HistoryMainForm()
    FirstForm = IndicatorsForm()
    MainDiagnosForm = HistoryMainDiagnosForm()
    OtherDiagnosForm = HistoryOtherDiagnosForm()
    NewAmbulanceForm = HistioryNewAmbulanceForm()
    NewHospitalForm_ = NewHospitalForm()

        # сохранение истории болезни
    if MainForm.submit.data and MainForm.validate_on_submit():
        pill = 1
        if history is None:
            # Это ввод новой истории
            history = CreateHistory(MainForm)
        else:
            # Обновление истории
            history = UpdateHistory(MainForm, h)

        if  history is not None:
            flash('Данные сохранены', category='info')
            return redirect(url_for('history.history_edit', h=history.id, pill=pill))

    if MainDiagnosForm.submit.data and MainDiagnosForm.validate_on_submit():
        pill = 3
        main_diagnose = AddMainDiagnos(MainDiagnosForm, history)
        if main_diagnose is not None:
            flash('Данные сохранены', category='info')

        return redirect(url_for('history.history_edit', h=history.id, pill=pill))

    if OtherDiagnosForm.submit.data and OtherDiagnosForm.validate_on_submit():
        pill = 3
        other_diagnose = AddOtherDiagnos(OtherDiagnosForm, history)
        if other_diagnose is not None:
            flash('Данные сохранены', category='info')

        return redirect(url_for('history.history_edit', h=history.id, pill=pill))

    if NewAmbulanceForm.submit.data and NewAmbulanceForm.validate_on_submit():
        pill = 4
        # Проверка существования такого типа приема
        hisory_event = HistoryEvents.query.filter(HistoryEvents.history==h, HistoryEvents.event==NewAmbulanceForm.event.data).first()
        if hisory_event is not None:
            flash('Амбулаторный прием такого типа уже существует', category='warning')
            return redirect(url_for('history.history_edit', h=history.id, pill=pill))
        else:
            # Переход в форму амбулаторного приема
            return redirect(url_for('history.ambulance_edit', h=history.id, h_e='0', e_type=NewAmbulanceForm.event.data, pill=1))

    if NewHospitalForm_.submit.data and NewHospitalForm_.validate_on_submit():
            # Переход в форму госпитализации
            return redirect(url_for('history.hospital_edit', h=history.id, h_e='0', pill=1))

    if history is not None:
        # Заполнение формы данными из базы
        form_list = FillHistoryForm(MainForm, FirstForm, MainDiagnosForm, history)
        MainForm = form_list[0]
        FirstForm = form_list[1]
        MainDiagnosForm = form_list[2]
        history_event_id = form_list[3].id
        items = form_list[4]
        diagnoses_items = form_list[5]
        ambulance_events = form_list[6]
        hospital_events = form_list[7]

    else:
        items = []
        history_event_id = 0
        diagnoses_items = []
        ambulance_events = []
        hospital_events = []

    return render_template('history/history_edit.html', HistoryMainForm=MainForm,
                            h=h, items = items, FirstForm=FirstForm,
                            MainDiagnosForm = MainDiagnosForm,
                            OtherDiagnosForm = OtherDiagnosForm,
                            NewAmbulanceForm = NewAmbulanceForm,
                            NewHospitalForm = NewHospitalForm_,
                            history_event_id = history_event_id,
                            diagnoses_items = diagnoses_items,
                            ambulance_events = ambulance_events,
                            hospital_events = hospital_events,
                            pill=pill)


# Сохранение показателей первичного обращения
@bp.route('/save_indicators/<h>/<h_e>/<pill>', methods = ['GET','POST'])
# Параметры:
# h - Histories.id
# h_e - HistoryEvents.id
# pill - номер закладки в форме
def save_indicators(h, h_e, pill):
    history_event = HistoryEvents.query.get(h_e)
    event = Events.query.get(history_event.event)
    event_type = event.type
    if 'save_indicators' in request.form: #and FirstForm.validate_on_submit():

        # Группа показателей
        indicator_group = request.form.get('indicator_group')
        if indicator_group == '2':
            # Это Рентгенография коленного сустава в двух проекциях
            text_values_1 = request.form.getlist('text_value_1')
            text_values_2 = request.form.getlist('text_value_2')
            text_values_3 = request.form.getlist('text_value_3')
            ids = request.form.getlist('indicator')
            for i, id in enumerate(ids):

                indicator_pzp = IndicatorValues.query.filter(IndicatorValues.history_event==h_e, IndicatorValues.slice=='Передне-задняя проекция',
                                                            IndicatorValues.indicator==id).first()
                if indicator_pzp:
                    indicator_pzp.text_value = text_values_1[i]
                    db.session.add(indicator_pzp)

                indicator_bp = IndicatorValues.query.filter(IndicatorValues.history_event==h_e, IndicatorValues.slice=='Боковая проекция',
                                                            IndicatorValues.indicator==id).first()
                if indicator_bp:
                    indicator_bp.text_value = text_values_2[i]
                    db.session.add(indicator_bp)

                indicator_r = IndicatorValues.query.filter(IndicatorValues.history_event==h_e, IndicatorValues.slice=='Результат',
                                                            IndicatorValues.indicator==id).first()
                if indicator_r:
                    indicator_r.text_value = text_values_3[i]
                    db.session.add(indicator_r)

            db.session.commit()
            flash('Данные сохранены', category='info')

        elif indicator_group == '4':
            # Это предоперационные обследования

app/templates/history/_AmbulanceForm.html
{% import "_macros.html" as m %}

{% macro AmbulanceForm(AmbulanceMainForm, h, history_event_id, event, items) %}
<form class="form-inline bg-light border" method="post">

      {{AmbulanceMainForm.csrf_token()}}
      {{ m.render_field(AmbulanceMainForm.event) }}
      {{ m.render_field(AmbulanceMainForm.doctor) }}
      {{ m.render_field(AmbulanceMainForm.date_begin) }}
      {{AmbulanceMainForm.submit(class='btn btn-primary')}}

</form>
<hr>
<form class="form bg-light" method="POST" action="{{url_for('history.save_indicators', h=h, h_e=history_event_id, pill=1)}}">
<input id="indicator_group" type = "hidden" class="form-control" name="indicator_group" type="number" value=11>
  <div class="row">
    <table class="table">
      <thead class="thead-light">
        <tr>
          <th scope="col">Показатель</th>
          <th scope="col">Значение</th>
          <th scope="col">Ед. измерения</th>
        </tr>
      </thead>
      <tbody>
        {% for i in items %}
        <tr>
          <input id="indicator_id" type = "hidden" class="form-control" name="indicator_id" type="number" value={{i.id}}>
          <td>{{i.description}}</td>
          <td>
            <input id="num_value" class="form-control" name="num_value" type="number" step="1" value={{i.num_value}}>
          </td>
          <td>
            <a>{{i.unit}}</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <p><input type="submit" class="btn-primary" name="save_indicators" value="Сохранить"></p>
</form>

{% endmacro%}

{% macro InstumentalForm(IndicatorsForm, h, history_event_id, items_2, pill) %}
<form class="form bg-light" method="POST" action="{{url_for('history.save_indicators', h=h, h_e=history_event_id, pill=2)}}">
  {{IndicatorsForm.csrf_token()}}
  <div class="form-row">
    <div class="col-3">
      <input id="indicator_group" type = "hidden" class="form-control" name="indicator_group" type="number" value=2>
    </div>
  </div>
  <div>
    <table class="table">
      <thead class="thead-light">
        <tr>
          <th scope="col">Показатель</th>
          <th scope="col">Передне-задняя проекция</th>
          <th scope="col">Боковая проекция</th>
          <th scope="col">Результат</th>
        </tr>
      </thead>
      <tbody>
        {% for i in items_2 %}
        <tr>
          <input id="indicator" type = "hidden" class="form-control" name="indicator" type="number" value={{i.indicator}}>
          <td>{{i.description}}</td>
          <td>
            <input id="text_value_1" class="form-control" name="text_value_1" type="text" maxlength="3" value={{i.text_value_1}}>
          </td>
          <td>
            <input id="text_value_2" class="form-control" name="text_value_2" type="text" maxlength="3" value={{i.text_value_2}}>
          </td>
          <td>
            <input id="text_value_3" class="form-control" name="text_value_3" type="text" maxlength="3" value={{i.text_value_3}}>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
<p><input type="submit" class="btn-primary" name="save_indicators" value="Сохранить"></p>
</form>
{% endmacro %}

{% macro Prosthesis(ProsthesisForm, h, history_event_id, pill) %}
<form class="form-inline bg-light border" method="post">

      {{ProsthesisForm.csrf_token()}}
      {{ m.render_field(ProsthesisForm.prosthesis) }}
      {{ProsthesisForm.submit(class='btn btn-primary')}}

</form>
{% endmacro %}


{% macro TelerentgenographyForm(TelerentgenographyForm, h, history_event_id, items_3, pill) %}
<form class="form bg-light" method="POST" action="{{url_for('history.save_indicators', h=h, h_e=history_event_id, pill=4)}}">
  {{TelerentgenographyForm.csrf_token()}}
  <div class="form-row">
    <div class="col-3">
      <input id="indicator_group" type = "hidden" class="form-control" name="indicator_group" type="number" value=3>
    </div>
  </div>
  <div>
    <table class="table">
      <thead class="thead-light">
        <tr>
          <th scope="col">Показатель</th>
          <th scope="col">Значение</th>
          <th scope="col">Ед измерения</th>
        </tr>
      </thead>
      <tbody>
        {% for i in items_3 %}
        <tr>
          <input id="indicator_id" type = "hidden" class="form-control" name="indicator_id" type="number" value={{i.id}}>
          <td>{{i.description}}</td>
          <td>
            <input id="num_value" class="form-control" name="num_value" type="number" step="1" min = 0 max=360 value={{i.num_value}}>
          </td>
          <td>
            <a>{{i.unit}}</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
<p><input type="submit" class="btn-primary" name="save_indicators" value="Сохранить"></p>
</form>
{% endmacro %}

{% macro PreoperativeForm(PreoperativeForm, h, history_event_id, items, pill) %}
<form class="form bg-light" method="POST" action="{{url_for('history.save_indicators', h=h, h_e=history_event_id, pill=5)}}">
  {{PreoperativeForm.csrf_token()}}
  <div class="form-row">
    <div class="col-3">
      <input id="indicator_group" type = "hidden" class="form-control" name="indicator_group" type="number" value=4>
    </div>
  </div>
  <div>
    <table class="table">
      <thead class="thead-light">
        <tr>
          <th scope="col">Показатель</th>
          <th scope="col">Есть исследования?</th>
        </tr>
      </thead>
      <tbody>
        {% for i in items %}
        <tr>
          <input id="indicator_id" type = "hidden" class="form-control" name="indicator_id" type="number" value={{i.id}}>
          <td>{{i.description}}</td>
          <td>
            <select class="form-control mx-1 my-1" id="select_value" name="select_value" required>
              {% if i.text_value == 'Да' %}
              <option selected value="Да">Да</option>
              <option value="Нет">Нет</option>
              {% else %}
              <option value="Да">Да</option>
              <option selected value="Нет">Нет</option>
              {% endif %}
            </select>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
<p><input type="submit" class="btn-primary" name="save_indicators" value="Сохранить"></p>
</form>
{% endmacro %}

app/templates/history/_HistoryMainForm.html
{% import "_macros.html" as m %}

{% macro HistoryMainForm(HistoryMainForm) %}
    <form class="form-inline bg-light justify-content-around" method="POST">
      {{HistoryMainForm.csrf_token()}}
      {{ m.render_field(HistoryMainForm.hist_number) }}
      {{ m.render_field(HistoryMainForm.date_in) }}
      {{ m.render_field(HistoryMainForm.clinic) }}
      {{ m.render_field(HistoryMainForm.snils) }}
      {{ m.render_field(HistoryMainForm.birthdate) }}
      {{ m.render_field(HistoryMainForm.sex) }}
      {{ m.render_field(HistoryMainForm.research_group) }}
      {{ m.render_field(HistoryMainForm.doctor_researcher) }}
      {{ m.render_field(HistoryMainForm.date_research_in) }}
      {{ m.render_field(HistoryMainForm.date_research_out) }}
      {{ m.render_field(HistoryMainForm.reason) }}
      <div class="row">
        <div class="col">
          {{HistoryMainForm.submit(class='btn btn-primary')}}
        </div>
      </div>
  </form>
{% endmacro %}

{% macro FirstForm(FirstForm, h, history_event_id, items, pill) %}
<form class="form bg-light" method="POST" action="{{url_for('history.save_indicators', h=h, h_e=history_event_id, pill=2)}}">
  {{FirstForm.csrf_token()}}
  <div class="form-row">
    <div class="col-3">
      {{ m.render_field(FirstForm.date_begin) }}
      <input id="indicator_group" type = "hidden" class="form-control" name="indicator_group" type="number" value=11>
    </div>
  </div>
  <div>
    <table class="table">
      <thead class="thead-light">
        <tr>
          <th scope="col">Показатель</th>
          <th scope="col">Значение</th>
          <th scope="col">Ед. измерения</th>
        </tr>
      </thead>
      <tbody>
        {% for i in items %}
        <tr>
          <input id="indicator_id" type = "hidden" class="form-control" name="indicator_id" type="number" value={{i.id}}>
          <td>{{i.description}}</td>
          <td>
            <input id="num_value" class="form-control" name="num_value" type="number" step="1" max=250 value={{i.num_value}}>
          </td>
          <td>
            <a>{{i.unit}}</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
<p><input type="submit" class="btn-primary" name="save_indicators" value="Сохранить"></p>
</form>
{% endmacro %}


{% macro DiagnosForm(MainDiagnosForm, OtherDiagnosForm, diagnoses_items, h, pill) %}
<!--Диагнозы-->
<!--Основной диагноз-->
<h5>Основной диагноз</h5>
<form class="form-inline bg-light border" method="post">
  {{MainDiagnosForm.csrf_token()}}
  {{ m.render_field(MainDiagnosForm.diagnos) }}
  {{ m.render_field(MainDiagnosForm.side_damage) }}
  {{ m.render_field(MainDiagnosForm.date_created) }}
  {{MainDiagnosForm.submit(class='btn btn-primary')}}
</form>
<table class="table">
  <thead class="thead-light">
    <tr>
      <th scope="col">Диагноз</th>
      <th scope="col">Шифр МКБ10</th>
      <th scope="col">Дата установления</th>
    </tr>
  </thead>
  <tbody>
    {% for item in diagnoses_items %}
    {% if item.type == 'Основной' %}
    <tr>
      <td>{{item.description}}</td>
      <td>{{item.mkb10}}</td>
      <td>{{item.date_created}}</td>
    {% endif %}
    {% endfor %}
    </tr>
  </tbody>
</table>
<hr>
<!--Сопутствующие диагнозы-->
<h5>Сопутствующий диагноз</h5>
<form class="form-inline bg-light border" method="post">
  {{OtherDiagnosForm.csrf_token()}}
  {{ m.render_field(OtherDiagnosForm.diagnos) }}
  {{ m.render_field(OtherDiagnosForm.date_created) }}
  {{OtherDiagnosForm.submit(class='btn btn-primary mx-1 my-1')}}
</form>

<table class="table">
  <thead class="thead-light">
    <tr>
      <th scope="col">Диагноз</th>
      <th scope="col">Шифр МКБ10</th>
      <th scope="col">Дата установления</th>
      <th scope="col"> </th>
    </tr>
  </thead>
  <tbody>
    {% for item in diagnoses_items %}
    <tr>
      <input id="diagnos_id" type = "hidden" class="form-control" name="diagnos_id" type="number" value={{item.id}}>
      <td>{{item.description}}</td>
      <td>{{item.mkb10}}</td>
      <td>{{item.date_created}}</td>
      <td>
      <a class="btn btn-danger" href="{{ url_for('history.diagnose_delete', h=h, d=item.id, pill=pill) }}">Удалить</a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endmacro %}

{% macro AmbulanceListForm(h, ambulance_events, NewAmbulanceForm) %}

<form class="form-inline bg-light border" method="post">
  {{NewAmbulanceForm.csrf_token()}}
  {{ m.render_field(NewAmbulanceForm.event) }}
  {{NewAmbulanceForm.submit(class='btn btn-primary')}}
</form>

<table class="table">
  <thead class="thead-light">
    <tr>
      <th scope="col">Дата</th>
      <th scope="col">Вид амбулаторного приема</th>
    </tr>
  </thead>
  <tbody>
     {% for ambulance_event in ambulance_events %}
    <tr>

      <td>
        <a href="{{ url_for('history.ambulance_edit', h=h, h_e=ambulance_event.event_id,
                            e_type=ambulance_event.event_type, pill=1) }}">{{ambulance_event.event_date}}</a>
      </td>
      <td>
        <a>{{ambulance_event.event_name}}</a>
      </td>

    </tr>
    {% endfor %}

  </tbody>
</table>

{% endmacro %}

{% macro HospitalListForm(h, hospital_events, NewHospitalForm) %}

<form class="form-inline bg-light border" method="post">
  {{NewHospitalForm.csrf_token()}}
  {{NewHospitalForm.submit(class='btn btn-primary')}}
</form>

<table class="table">
  <thead class="thead-light">
    <tr>
      <th scope="col">Дата госпитализации</th>
      <th scope="col">Дата выписки</th>
      <th scope="col">Лечащий врач</th>
    </tr>
  </thead>
  <tbody>
     {% for hospital in hospital_events %}
    <tr>

      <td>
        <a href="{{ url_for('history.hospital_edit', h=h, h_e=hospital.event_id,
                            pill=1) }}">{{hospital.event_date_begin}}</a>
      </td>
      <td>
        <a>{{hospital.event_date_begin}}</a>
      </td>
      <td>
        <a>{{hospital.doctor}}</a>
      </td>

    </tr>
    {% endfor %}

  </tbody>
</table>


{% endmacro %}

app/templates/history/_HospitalForm.html
{% import "_macros.html" as m %}

{% macro HospitalSubForm1(HospitalSubForm1, pill) %}
    <form class="form-inline bg-light justify-content-around" method="POST">
      {{HospitalSubForm1.csrf_token()}}
      {{ m.render_field(HospitalSubForm1.date_begin) }}
      {{ m.render_field(HospitalSubForm1.date_end) }}
      {{ m.render_field(HospitalSubForm1.doctor) }}
      {{ m.render_field(HospitalSubForm1.doctor_chief) }}
      {{ m.render_field(HospitalSubForm1.days1, disabled=True) }}
      {{ m.render_field(HospitalSubForm1.days2, disabled=True) }}
      {{ m.render_field(HospitalSubForm1.days3, disabled=True) }}
      <div class="row">
        <div class="col">
          {{HospitalSubForm1.submit(class='btn btn-primary')}}
        </div>
      </div>
  </form>
{% endmacro %}

{% macro HospitalSubForm2(HospitalSubForm2, history, h_e, items, pill) %}
<form class="form-inline bg-light" method="POST" action="{{url_for('history.save_indicators', h=history.id, h_e=h_e, pill=2)}}">
  <input id="indicator_group" type = "hidden" class="form-control" name="indicator_group" type="number" value=5>
      {{HospitalSubForm2.csrf_token()}}
      <div class="col-3">
        {{ m.render_field(HospitalSubForm2.date_begin) }}
      </div>
      <div class="col-3">
        {{HospitalSubForm2.save_indicators(class='btn btn-primary')}}
      </div>
<hr>

    <table class="table">
      <thead class="thead-light">
        <tr>
          <th scope="col">Показатель</th>
          <th scope="col">Значение</th>
          <th scope="col">Комментарий</th>
        </tr>
      </thead>
      <tbody>
        <!--Жалобы-->
        {{ m.table_row(field=HospitalSubForm2.claims, indicator_name='Жалобы', indicator_id=49, items=items)}}
        <!--Анамнез заболевания: жалобы в течение -->
        {{ m.table_row(field=HospitalSubForm2.claims_time, indicator_name='Анамнез заболевания: жалобы в течение', indicator_id=50, items=items)}}
        <!--Анамнез жизни: Перенесенные заболевания  -->
        {{ m.table_row(field=HospitalSubForm2.diseases, indicator_name='Анамнез жизни: Перенесенные заболевания', indicator_id=51, items=items)}}
        <!--Анамнез жизни: Операции, травмы  -->
        {{ m.table_row(field=HospitalSubForm2.traumas, indicator_name='Анамнез жизни: Операции, травмы', indicator_id=52, items=items)}}
        <!--Курение   -->
        {{ m.table_row(field=HospitalSubForm2.smoking, indicator_name='Курение', indicator_id=53, items=items)}}
        <!--Алкоголь   -->
        {{ m.table_row(field=HospitalSubForm2.alcohol, indicator_name='Алкоголь', indicator_id=54, items=items)}}
        <!--Аллергологический анамнез   -->
        {{ m.table_row(field=HospitalSubForm2.allergy, indicator_name='Аллергологический анамнез', indicator_id=55, items=items)}}
        <!--Наследственные заболевания   -->
        {{ m.table_row(field=HospitalSubForm2.genetic, indicator_name='Наследственные заболевания', indicator_id=56, items=items)}}

      </tbody>
    </table>


</form>
{% endmacro %}

app/templates/history/history_select.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "_macros.html" as macros %}
{% block page_content %}
<div class="card">
  <div class="card-header m-0">
    <h5>{{title}}</h5>
  </div>
  <div class="card-body">
        <!--Панель выборки историй болезни-->

        <div class="row">
          <div class="col">
            <form class="form-inline my-2 p-2 bg-light text-muted justify-content-around" method="POST">
              {{HistoryFilterForm.csrf_token()}}
              <div class="form-group">
                {{HistoryFilterForm.snils_filter.label(class="form-control-label mx-2")}}
                {{HistoryFilterForm.snils_filter(class="form-control")}}
              </div>
              <div class="form-group">
                {{HistoryFilterForm.clinic_filter.label(class="form-control-label mx-2")}}
                {{HistoryFilterForm.clinic_filter(class="form-control")}}
              </div>
                {{HistoryFilterForm.submit_filter(class='btn btn-primary')}}
              <!--<input type="button" class="btn btn-primary" value="set_filter" >
              <a class="btn btn-outline-primary" href="{{url_for('admin.user_role')}}">Фильтр</a> -->
            </form>
          </div>
        </div>
        <!--end of фильтр таблицы-->
        <div class="row">
          <div class="col">
            <!--Таблица-->
            <table class="table">
              <thead class="thead-light">
                <tr>
                  <th scope="col">№</th>
                  <th scope="col">Клиника</th>
                  <th scope="col">Дата создания</th>
                  <th scope="col">Дата включения в исследование</th>
                  <th scope="col">Дата исключения из исследования</th>
                </tr>
              </thead>
              <tbody>
                {% for h in histories %}
                <tr>
                  <td>
                    <a href="{{ url_for('.history_edit', h=h.id, pill=1) }}">{{h.hist_number}}</a>
                  </td>
                  <td>{{h.clinic}}</td>
                  <td>{{h.date_in}}</td>
                  <td>{{h.date_research_in}}</td>
                  <td>{{h.date_research_out}}</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
            <!--end of Таблица-->
          </div>
        </div>
        {{ macros.pagination_w(pagination, 'history.history_select') }}
      </div>
      <div class="card-footer">

      </div>
    </div>
{% endblock %}